[package]
name = "dtm"
version = "0.1.0"
authors = ["ndts55 <nicolastorres@mailbox.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
